<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Users_model extends CI_Model
{

    public $table = 'users';
    public $v_table = 'v_users';
    public $id = 'id';
    public $login = 'login';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->v_table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->v_table)->row();
    }
    // get data by username
    function get_by_login($login)
    {
        $this->db->where($this->login, $login);
        return $this->db->get($this->v_table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('empno', $q);
	$this->db->or_like('first_name', $q);
	$this->db->or_like('last_name', $q);
	$this->db->or_like('login', $q);
	$this->db->or_like('pass', $q);
	$this->db->or_like('id_type', $q);
	$this->db->or_like('id_departement', $q);
	$this->db->or_like('mgr_empno', $q);
	$this->db->or_like('general_m', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('empno', $q);
	$this->db->or_like('first_name', $q);
	$this->db->or_like('last_name', $q);
	$this->db->or_like('login', $q);
	$this->db->or_like('pass', $q);
	$this->db->or_like('id_type', $q);
	$this->db->or_like('id_departement', $q);
	$this->db->or_like('mgr_empno', $q);
	$this->db->or_like('general_m', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->v_table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Users_model.php */
/* Location: ./application/models/Users_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-10-15 22:40:45 */
/* http://harviacode.com */